project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!alextejadastrop-ready-exercise/**"

website:
  title: "MADA Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: MADA Group Projects
      - href: class-project/index.qmd
        text: Class Individual Project
      - href: data-exercise/data-exercise.qmd
        text: Data Exercise (Synthetic)
      - href: starter-analysis-exercise.qmd
        text: Starter Analysis Exercise
      - href: contacts.qmd
        text: Contact / Links
    right:
      - icon: github
        href: https://github.com/alex8528/mada-portfolio

format:
  html:
    theme: cosmo
    toc: true
